### ISSUE TITLE
Outdated security advisory flow

### ISSUE THREAD

**Issue by mratsim** [dd86k/sha3-d#8]
The suggested security advisory flow is incorrect, probably refering to an old workflow.

https://github.com/dd86k/sha3-d/blob/dc34beb92f28bdbeb30b0e360254dbbaf7a21e92/.github/SECURITY.md#L5-L6

In the current Github, only admins can create a security advisory so people have to contact you privately:

https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory

> Who can use this feature
>
> Anyone with admin permissions to a repository, or with a security manager role within the repository, can create a security advisory.

Note: I don't have any security issue to report. Was just curious.

**Comment by dd86k** [comment]
Hey, thanks for noticing.

I've enabled [Private vulnerability reporting (Beta)](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability), which "Allow your community to privately report potential security vulnerabilities to maintainers and repository owners.". Hoping this will work.

I've also noticed a typo in the snippet that you highlighted (regarding "Securitiy"), I'll tweak the SECURITY.md file later and apply it to my blake2 repo as well.
